POST http://localhost:4000/api/tenants HTTP/1.1
Content-Type: application/json

{
  "name":"Eric Ndege",
  "email": "Ndege@gmail.com",
  "phoneNumber": "+254726168677",
  "rent": 2500,
  "property": "6858452da561b75ac0cff840"
}

###
PATCH http://localhost:4000/api/tenants/685860fd29d6584fc2ecc4cf
Content-Type: application/json

{
  "name": "Jane Ndege"
}

###

GET http://localhost:4000/api/properties HTTP/1.1

###
GET  http://localhost:4000/api/tenants/ HTTP/1.1

###
PATCH  http://localhost:4000/api/tenants/685860fd29d6584fc2ecc4cf HTTP/1.1
Content-Type: application/json

{
  "property": "6859b10892ac139bade5ee18"
}

###

GET http://localhost:4000/api/users  HTTP/1.1

###
  
PATCH  http://localhost:4000/api/users/684efbd288c7b2b822b2ad35 HTTP/1.1
Content-Type: application/json

{
  "name": "Test map",
  "password": "Testing@2026",
  "email": "test@gmail.com"
}

###
DELETE http://localhost:4000/api/properties/6859b18092ac139bade5ee21 HTTP/1.1

###
DELETE  http://localhost:4000/api/txns/685adabf74fbde745dc2d92f HTTP/1.1

###
GET http://localhost:4000/api/txns/ HTTP/1.1